project_id = "kbjxdrbscmiqykurvoep"

[functions.whatsapp-notify]
verify_jwt = false

[functions.translate-menu-item]
verify_jwt = false

[functions.translate-menu-category]
verify_jwt = false

[functions.translate-all-menu]
verify_jwt = false

[functions.create-chat-order]
verify_jwt = false

[functions.create-driver]
verify_jwt = false
